name: flutter_sms_example
description: Demonstrates how to use the flutter_sms plugin.
publish_to: 'none'

environment:
  dk: '>=2.12.0-259.8.beta <=3.5.3'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_sms:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

